### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by iantmoore**
Range of updates, fixes and modifications to facilitate an IntelliJ plugin.
 
* Built a caller hierarchy and determined substep definitions that are not called in the current scope.  
* Defensive code around early failure and an IndexOutOfBounds plus an error when no substeps files supplied.
* Fixed issue around passing of variables into substeps when running in non strict mode
* refactoring of the JMX server to return byte representations of results, wrapping setup failures inside the root node
* Corrected the order of setting node state and sending out notifications

### CODE REVIEW

**Comment by iantmoore** [comment]
hmm, that build failure is because Travis can't see the substeps-api snapshot that these changes depend on...  I wonder if this is a good case for having a single repo containing api, core and the runners...?

**Comment by iantmoore** [comment]
hmm, that build failure is because Travis can't see the substeps-api snapshot that these changes depend on...  I wonder if this is a good case for having a single repo containing api, core and the runners...?

**Comment by iantmoore** [comment]
this build does actually pass when built against the correct snapshot versions.. see https://github.com/iantmoore/substeps-uber which uses submodules and a single travis build

**Comment by beercan1989** [comment]
Hmm, I'm going to accept the changes and accept the fact that Travis will complain.

Next plan will be to work out the best way to resolve the issue, such as combine the actual core of Substeps into one GitHub repository but still keep them isolated modules.

**Comment by beercan1989** [comment]
Have run this pull request on our (G2G3 Digital) CI stack and they pass, as we have access to the snapshot versions from substeps-api repository.

**Pull request merged**
